import { Project, Transaction, ProjectStatus, Category, MonthlyBudget, ActivityLog } from "./types";

export const COMPANY_INFO = {
  name: "CV. MANDIRI CIPTA JAYA x PT. ELQIA JAYA TEKNIK",
  subName: "Civil - M&E - Perdagangan umum & Jasa",
  address: "Perum griya panorama indah Blok C9 No.26 Purwasari - Karawang",
  phone: "Hp : 0812 1960 5114 / 0897 6350 688",
  email: "Email : mandiricipta_jaya@yahoo.com",
};

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-ho-mcj",
    name: "HO MCJ",
    code: "HO.MCJ.2026",
    manager: "Direksi",
    pic: "Direksi",
    status: ProjectStatus.PROGRES,
    startDate: "2026-01-01",
    expectedProfitPercent: 100,
    contractValue: { piping: 0, electrical: 0, mechanical: 0, scafolder: 0, welder: 0 },
    ppnPercent: 0,
    pphPercent: 0,
    budgetThresholdPercent: 100,
    notes: "Head Office CV. Mandiri Cipta Jaya (Tanpa PPN & PPh)",
    company: "CV. Mandiri Cipta Jaya",
    customContractItems: [],
  },
  {
    id: "proj-ho-ejt",
    name: "HO EJT",
    code: "HO.EJT.2026",
    manager: "Direksi",
    pic: "Direksi",
    status: ProjectStatus.PROGRES,
    startDate: "2026-01-01",
    expectedProfitPercent: 100,
    contractValue: { piping: 0, electrical: 0, mechanical: 0, scafolder: 0, welder: 0 },
    ppnPercent: 0,
    pphPercent: 0,
    budgetThresholdPercent: 100,
    notes: "Head Office PT. Elqia Jaya Teknik (Tanpa PPN & PPh)",
    company: "PT. Elqia Jaya Teknik",
    customContractItems: [],
  },
  {
    id: "proj-smart-marunda",
    name: "PT SMART MARUNDA",
    code: "TSRT.SMART.001.2026",
    manager: "BPK. Ujang N",
    pic: "P Haryanto",
    status: ProjectStatus.PROGRES,
    startDate: "2026-03-01",
    expectedProfitPercent: 35,
    contractValue: {
      piping: 1100000000,
      electrical: 330000000,
      mechanical: 58000000,
      scafolder: 51000000,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 85,
    notes: "Proyek instalasi piping, electrical, mechanical, dan scaffolding untuk PT Smart Marunda.",
    company: "CV. Mandiri Cipta Jaya",
    targetCompletionDate: "2026-07-25",
    customContractItems: [
      { id: "piping", name: "Piping", value: 1100000000 },
      { id: "electrical", name: "Electrical", value: 330000000 },
      { id: "mechanical", name: "Mechanical", value: 58000000 },
      { id: "scafolder", name: "Scafolder", value: 51000000 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  },
  {
    id: "proj-aicc",
    name: "PT Aicc Indonesia",
    code: "TSRT.AICC.002.2026",
    manager: "P M Suryadi",
    pic: "P M Suryadi",
    status: ProjectStatus.PROGRES,
    startDate: "2026-01-15",
    expectedProfitPercent: 30,
    contractValue: {
      piping: 0,
      electrical: 0,
      mechanical: 0,
      scafolder: 0,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 90,
    notes: "Proyek Sipil & Mekanikal Gedung Aicc Utama.",
    company: "CV. Mandiri Cipta Jaya",
    customContractItems: [
      { id: "piping", name: "Piping", value: 0 },
      { id: "electrical", name: "Electrical", value: 0 },
      { id: "mechanical", name: "Mechanical", value: 0 },
      { id: "scafolder", name: "Scafolder", value: 0 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  },
  {
    id: "proj-rockpain",
    name: "PT Rockpain Industri",
    code: "TSRT.ROCK.003.2026",
    manager: "P Dede",
    pic: "P Dede",
    status: ProjectStatus.PROGRES,
    startDate: "2026-02-10",
    expectedProfitPercent: 28,
    contractValue: {
      piping: 0,
      electrical: 0,
      mechanical: 0,
      scafolder: 0,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 80,
    company: "CV. Mandiri Cipta Jaya",
    customContractItems: [
      { id: "piping", name: "Piping", value: 0 },
      { id: "electrical", name: "Electrical", value: 0 },
      { id: "mechanical", name: "Mechanical", value: 0 },
      { id: "scafolder", name: "Scafolder", value: 0 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  },
  {
    id: "proj-oji-indo",
    name: "PT Oji Indo Makmur",
    code: "TSRT.OJI.004.2026",
    manager: "P Lily",
    pic: "P Lily",
    status: ProjectStatus.PROGRES,
    startDate: "2026-04-01",
    expectedProfitPercent: 32,
    contractValue: {
      piping: 0,
      electrical: 0,
      mechanical: 0,
      scafolder: 0,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 85,
    company: "PT. Elqia Jaya Teknik",
    customContractItems: [
      { id: "piping", name: "Piping", value: 0 },
      { id: "electrical", name: "Electrical", value: 0 },
      { id: "mechanical", name: "Mechanical", value: 0 },
      { id: "scafolder", name: "Scafolder", value: 0 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  },
  {
    id: "proj-oji-sinar",
    name: "PT Oji Sinar Mas",
    code: "TSRT.OSM.005.2026",
    manager: "P Teni",
    pic: "P Teni",
    status: ProjectStatus.CLOSING,
    startDate: "2025-09-01",
    expectedProfitPercent: 35,
    contractValue: {
      piping: 0,
      electrical: 0,
      mechanical: 0,
      scafolder: 0,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 85,
    notes: "Proyek selesai dengan profit memuaskan.",
    company: "PT. Elqia Jaya Teknik",
    customContractItems: [
      { id: "piping", name: "Piping", value: 0 },
      { id: "electrical", name: "Electrical", value: 0 },
      { id: "mechanical", name: "Mechanical", value: 0 },
      { id: "scafolder", name: "Scafolder", value: 0 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  },
  {
    id: "proj-daiki",
    name: "PT Daiki Machinery",
    code: "TSRT.DKI.006.2026",
    manager: "P Itandi",
    pic: "P Itandi",
    status: ProjectStatus.CLOSING,
    startDate: "2025-10-10",
    expectedProfitPercent: 30,
    contractValue: {
      piping: 0,
      electrical: 0,
      mechanical: 0,
      scafolder: 0,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 85,
    company: "PT. Elqia Jaya Teknik",
    customContractItems: [
      { id: "piping", name: "Piping", value: 0 },
      { id: "electrical", name: "Electrical", value: 0 },
      { id: "mechanical", name: "Mechanical", value: 0 },
      { id: "scafolder", name: "Scafolder", value: 0 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  },
  {
    id: "proj-istw",
    name: "PT Istw Steel",
    code: "TSRT.ISTW.007.2026",
    manager: "P Rifky",
    pic: "P Rifky",
    status: ProjectStatus.CLOSING,
    startDate: "2025-11-01",
    expectedProfitPercent: 33,
    contractValue: {
      piping: 0,
      electrical: 0,
      mechanical: 0,
      scafolder: 0,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 85,
    company: "PT. Elqia Jaya Teknik",
    customContractItems: [
      { id: "piping", name: "Piping", value: 0 },
      { id: "electrical", name: "Electrical", value: 0 },
      { id: "mechanical", name: "Mechanical", value: 0 },
      { id: "scafolder", name: "Scafolder", value: 0 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  },
  {
    id: "proj-firelli-mru",
    name: "PT Firelli MRU",
    code: "TSRT.FMRU.008.2026",
    manager: "Office",
    pic: "Office",
    status: ProjectStatus.CLOSING,
    startDate: "2025-08-15",
    expectedProfitPercent: 35,
    contractValue: {
      piping: 0,
      electrical: 0,
      mechanical: 0,
      scafolder: 0,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 85,
    company: "CV. Mandiri Cipta Jaya",
    customContractItems: [
      { id: "piping", name: "Piping", value: 0 },
      { id: "electrical", name: "Electrical", value: 0 },
      { id: "mechanical", name: "Mechanical", value: 0 },
      { id: "scafolder", name: "Scafolder", value: 0 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  },
  {
    id: "proj-firelli-member",
    name: "PT Firelli Member",
    code: "TSRT.FMEM.009.2026",
    manager: "P Wawan",
    pic: "P Wawan",
    status: ProjectStatus.CANCEL,
    startDate: "2025-12-01",
    expectedProfitPercent: 30,
    contractValue: {
      piping: 0,
      electrical: 0,
      mechanical: 0,
      scafolder: 0,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 85,
    notes: "Proyek dibatalkan oleh pihak klien setelah tahap persiapan.",
    company: "CV. Mandiri Cipta Jaya",
    customContractItems: [
      { id: "piping", name: "Piping", value: 0 },
      { id: "electrical", name: "Electrical", value: 0 },
      { id: "mechanical", name: "Mechanical", value: 0 },
      { id: "scafolder", name: "Scafolder", value: 0 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  },
  {
    id: "proj-mti-kendal",
    name: "PT MTI Kendal",
    code: "TSRT.MTI.010.2026",
    manager: "BPK. Ujang N",
    pic: "P Ujang",
    status: ProjectStatus.PROGRES,
    startDate: "2026-05-15",
    expectedProfitPercent: 35,
    contractValue: {
      piping: 0,
      electrical: 0,
      mechanical: 0,
      scafolder: 0,
      welder: 0,
    },
    ppnPercent: 11,
    pphPercent: 4,
    budgetThresholdPercent: 85,
    company: "PT. Elqia Jaya Teknik",
    customContractItems: [
      { id: "piping", name: "Piping", value: 0 },
      { id: "electrical", name: "Electrical", value: 0 },
      { id: "mechanical", name: "Mechanical", value: 0 },
      { id: "scafolder", name: "Scafolder", value: 0 },
      { id: "welder", name: "Welder", value: 0 },
    ],
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // MARCH PETY CASH (Rp 13.500.000)
  {
    id: "tx-m-01",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Wawan",
    date: "2026-03-06",
    petyCashNo: "PC-001",
    status: "Sudah Proses",
    description: "Sewa Mess 2 Pintu Periode 09 Maret s.d 08 April 26",
    category: "Mess karyawan",
    paymentMethod: "Tunai",
    amount: 3000000,
  },
  {
    id: "tx-m-02",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Wawan",
    date: "2026-03-06",
    petyCashNo: "PC-002",
    status: "Sudah Proses",
    description: "Biaya Operasional Project",
    category: "Lain - Lain",
    paymentMethod: "Tunai",
    amount: 1000000,
  },
  {
    id: "tx-m-03",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-03-26",
    petyCashNo: "PC-003",
    status: "Sudah Proses",
    description: "Sewa Mess ( Penambahan 2 Kamar )",
    category: "Mess karyawan",
    paymentMethod: "Tunai",
    amount: 3000000,
  },
  {
    id: "tx-m-04",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-03-26",
    petyCashNo: "PC-003",
    status: "Sudah Proses",
    description: "Pembelian Kasur Lantai",
    category: "Mess karyawan",
    paymentMethod: "Tunai",
    amount: 600000,
  },
  {
    id: "tx-m-05",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-03-26",
    petyCashNo: "PC-003",
    status: "Sudah Proses",
    description: "Ongkos 2 Orang Scaffolder dari Indramayu",
    category: "Transportasi",
    paymentMethod: "Tunai",
    amount: 500000,
  },
  {
    id: "tx-m-06",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-03-26",
    petyCashNo: "PC-003",
    status: "Sudah Proses",
    description: "BOP Project",
    category: "Lain - Lain",
    paymentMethod: "Tunai",
    amount: 1400000,
  },
  {
    id: "tx-m-07",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Rifky",
    date: "2026-03-26",
    petyCashNo: "PC-004",
    status: "Sudah Proses",
    description: "Pembelian Kaos dan Sablon 100 Pcs",
    category: "Perlengkapan Pelindung",
    paymentMethod: "Tunai",
    amount: 4000000,
  },

  // APRIL PETY CASH (Rp 57.571.421)
  {
    id: "tx-a-01",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-02",
    petyCashNo: "PC-005",
    status: "Sudah Proses",
    description: "BOP 2 Mingguan Pak Sonni Periode 03 s.d 17 April 26",
    category: "Lain - Lain",
    paymentMethod: "Tunai",
    amount: 700000,
  },
  {
    id: "tx-a-02",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-02",
    petyCashNo: "PC-006",
    status: "Sudah Proses",
    description: "BPJS TK JAKON Project Smart Electrical",
    category: "BPJS JAKON",
    paymentMethod: "Tunai",
    amount: 677000,
  },
  {
    id: "tx-a-03",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-06",
    petyCashNo: "PC-007",
    status: "Sudah Proses",
    description: "BBM & Air Minum",
    category: "Air Minum",
    paymentMethod: "Tunai",
    amount: 1363000,
  },
  {
    id: "tx-a-04",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-06",
    petyCashNo: "PC-007",
    status: "Sudah Proses",
    description: "BBM + E Toll Antar Tools",
    category: "Transportasi",
    paymentMethod: "Tunai",
    amount: 470000,
  },
  {
    id: "tx-a-05",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-06",
    petyCashNo: "PC-007",
    status: "Sudah Proses",
    description: "Pembelian Face Shild ( 3 Pcs ), Oli Bromus ( 2 L ) & Kikir Bulat ( 1 Pcs )",
    category: "Consumable",
    paymentMethod: "Tunai",
    amount: 330000,
  },
  {
    id: "tx-a-06",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-06",
    petyCashNo: "PC-007",
    status: "Sudah Proses",
    description: "Mess 2 Kamar Periode 11 April s.d 10 Mei 26",
    category: "Mess karyawan",
    paymentMethod: "Tunai",
    amount: 3000000,
  },
  {
    id: "tx-a-07",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-06",
    petyCashNo: "PC-008",
    status: "Sudah Proses",
    description: "Pembayaran Tools Jaya Teknik Periode 30 Maret 26",
    category: "Tools",
    paymentMethod: "Transfer",
    amount: 3374000,
  },
  {
    id: "tx-a-08",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-10",
    petyCashNo: "PC-009",
    status: "Sudah Proses",
    description: "BPJS Jakon Project Smart Piping",
    category: "BPJS JAKON",
    paymentMethod: "Tunai",
    amount: 1870000,
  },
  {
    id: "tx-a-09",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-10",
    petyCashNo: "PC-010",
    status: "Sudah Proses",
    description: "BOP Project",
    category: "Lain - Lain",
    paymentMethod: "Tunai",
    amount: 1000000,
  },
  {
    id: "tx-a-10",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-10",
    petyCashNo: "PC-010",
    status: "Sudah Proses",
    description: "Pembelian Tools & Consumable ( Tespen, Scun, Clamp, Stanglass, Dll )",
    category: "Tools",
    paymentMethod: "Tunai",
    amount: 500000,
  },
  {
    id: "tx-a-11",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-10",
    petyCashNo: "PC-011",
    status: "Sudah Proses",
    description: "Tig torch stang las argon wp26 v wp26v merk Weldcraft",
    category: "Tools",
    paymentMethod: "Transfer",
    amount: 2400000,
  },
  {
    id: "tx-a-12",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-10",
    petyCashNo: "PC-011",
    status: "Sudah Proses",
    description: "Tig torch stang las argon wp26 v wp26v Lokal",
    category: "Tools",
    paymentMethod: "Transfer",
    amount: 300000,
  },
  {
    id: "tx-a-13",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-20",
    petyCashNo: "PC-012",
    status: "Sudah Proses",
    description: "BOP 2 Mingguan Pak Sonni Periode 18 s.d 01 Mei 26",
    category: "Lain - Lain",
    paymentMethod: "Tunai",
    amount: 700000,
  },
  {
    id: "tx-a-14",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-23",
    petyCashNo: "PC-013",
    status: "Sudah Proses",
    description: "Penggantian Kontrakan Rumah Besar",
    category: "Mess karyawan",
    paymentMethod: "Tunai",
    amount: 1500000,
  },
  {
    id: "tx-a-15",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-23",
    petyCashNo: "PC-013",
    status: "Sudah Proses",
    description: "BBM + Air Minum",
    category: "Air Minum",
    paymentMethod: "Tunai",
    amount: 1000000,
  },
  {
    id: "tx-a-16",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-04-23",
    petyCashNo: "PC-013",
    status: "Sudah Proses",
    description: "Perlengkapan Mess ( 5 Kasur + 3 Kipas angin )",
    category: "Mess karyawan",
    paymentMethod: "Tunai",
    amount: 1400000,
  },
  {
    id: "tx-a-17",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-24",
    petyCashNo: "PC-015",
    status: "Sudah Proses",
    description: "Pembelian Mesin Trafo Izumi Tig 200A 3 Unit",
    category: "Tools",
    paymentMethod: "Transfer",
    amount: 9100000,
  },
  {
    id: "tx-a-18",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-24",
    petyCashNo: "PC-016",
    status: "Sudah Proses",
    description: "Sarung Tangan 100 Lusin",
    category: "Perlengkapan Pelindung",
    paymentMethod: "Transfer",
    amount: 2100000,
  },
  {
    id: "tx-a-19",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-27",
    petyCashNo: "PC-017",
    status: "Sudah Proses",
    description: "Helmet Tanizawa Putih 0169 @ 40 Pcs x 290.000",
    category: "Perlengkapan Pelindung",
    paymentMethod: "Transfer",
    amount: 11600000,
  },
  {
    id: "tx-a-20",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-27",
    petyCashNo: "PC-017",
    status: "Sudah Proses",
    description: "Ongkir Pengiriman Perlengkapan",
    category: "Transportasi",
    paymentMethod: "Tunai",
    amount: 400000,
  },
  {
    id: "tx-a-21",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-27",
    petyCashNo: "PC-017",
    status: "Sudah Proses",
    description: "Rompi @ 100 Pcs x 95.000 + Ongkir Rp. 35.000",
    category: "Perlengkapan Pelindung",
    paymentMethod: "Transfer",
    amount: 9535000,
  },
  {
    id: "tx-a-22",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-30",
    petyCashNo: "PC-018",
    status: "Sudah Proses",
    description: "Tig torch stang las argon wp26 v wp26v merk Weldcraft / 1 Pcs",
    category: "Tools",
    paymentMethod: "Transfer",
    amount: 2303750,
  },
  {
    id: "tx-a-23",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-30",
    petyCashNo: "PC-018",
    status: "Sudah Proses",
    description: "Senter Kepala 60W / 5 Pcs",
    category: "Tools",
    paymentMethod: "Transfer",
    amount: 441000,
  },
  {
    id: "tx-a-24",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-30",
    petyCashNo: "PC-018",
    status: "Sudah Proses",
    description: "Regulator LPG dan Oxygen YAMATO 1 Set",
    category: "Consumable",
    paymentMethod: "Transfer",
    amount: 238500,
  },
  {
    id: "tx-a-25",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-30",
    petyCashNo: "PC-018",
    status: "Sudah Proses",
    description: "Cutting Torch Strong 8\" 1 Pcs",
    category: "Tools",
    paymentMethod: "Transfer",
    amount: 197100,
  },
  {
    id: "tx-a-26",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-30",
    petyCashNo: "PC-018",
    status: "Sudah Proses",
    description: "Tig Torch \"Rhino\" Wp 26 / 2 Pcs",
    category: "Tools",
    paymentMethod: "Transfer",
    amount: 872071,
  },
  {
    id: "tx-a-27",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-30",
    petyCashNo: "PC-018",
    status: "Sudah Proses",
    description: "Biaya Ongkir Lainnya",
    category: "Transportasi",
    paymentMethod: "Tunai",
    amount: 200000,
  },

  // LARGER GAJI ENTRIES FROM PAGE 3 (Gaji totals per month: Rp 797.017.035 in total)
  {
    id: "tx-gaji-01",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-03-25",
    petyCashNo: "GAJI-01",
    status: "Sudah Proses",
    description: "Gaji Karyawan Lapangan & Staff Periode Maret",
    category: "Gaji",
    paymentMethod: "Transfer",
    amount: 23670000,
  },
  {
    id: "tx-gaji-02",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-04-25",
    petyCashNo: "GAJI-02",
    status: "Sudah Proses",
    description: "Gaji Karyawan Lapangan & Staff Periode April",
    category: "Gaji",
    paymentMethod: "Transfer",
    amount: 172807285,
  },
  {
    id: "tx-gaji-03",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-05-25",
    petyCashNo: "GAJI-03",
    status: "Sudah Proses",
    description: "Gaji Karyawan Lapangan & Staff Periode Mei",
    category: "Gaji",
    paymentMethod: "Transfer",
    amount: 410311750,
  },
  {
    id: "tx-gaji-04",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-06-25",
    petyCashNo: "GAJI-04",
    status: "Sudah Proses",
    description: "Gaji Karyawan Lapangan & Staff Periode Juni",
    category: "Gaji",
    paymentMethod: "Transfer",
    amount: 190228000,
  },

  // OTHER ACTUAL DATA FROM PAGE 3 (Ppn 11%, Dana 2%, FEE MARKET, ATK, etc)
  {
    id: "tx-ppn-ho",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-03-10",
    petyCashNo: "HO-01",
    status: "Sudah Laporan",
    description: "Pembayaran Ppn 11% Kantor Pusat",
    category: "Ppn 11%",
    paymentMethod: "Transfer",
    amount: 195778000,
  },
  {
    id: "tx-dana-ho",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-03-10",
    petyCashNo: "HO-02",
    status: "Sudah Laporan",
    description: "Alokasi Dana HO 2% Project",
    category: "Dana 2%",
    paymentMethod: "Transfer",
    amount: 28600000,
  },
  {
    id: "tx-fee-market",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-06-15",
    petyCashNo: "FEE-01",
    status: "Sudah Laporan",
    description: "Pembayaran FEE MARKET Project",
    category: "FEE MARKET",
    paymentMethod: "Transfer",
    amount: 106740000,
  },

  // MEI PETY CASH ADDITIONAL SEEDING
  {
    id: "tx-mei-add-01",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-05-05",
    petyCashNo: "PC-019",
    status: "Sudah Proses",
    description: "BOP 2 Mingguan Periode 05 sd 20 Mei 2026",
    category: "Lain - Lain",
    paymentMethod: "Tunai",
    amount: 700000,
  },
  {
    id: "tx-mei-add-02",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-05-05",
    petyCashNo: "PC-020",
    status: "Sudah Proses",
    description: "PEMBELIAN CRAMIC NO 07 (10 PCS) @ 8.000",
    category: "Consumable",
    paymentMethod: "Tunai",
    amount: 80000,
  },
  {
    id: "tx-mei-add-03",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-05-05",
    petyCashNo: "PC-020",
    status: "Sudah Proses",
    description: "PEMBELIAN CLAMP SELANG 1/2 (10 PCS) @ 2.000",
    category: "Consumable",
    paymentMethod: "Tunai",
    amount: 20000,
  },
  {
    id: "tx-mei-add-04",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "Office",
    date: "2026-05-05",
    petyCashNo: "PC-020",
    status: "Sudah Proses",
    description: "PEMBELIAN STANG LASS STIG 800A / 500A (5 PCS) @ 80.000",
    category: "Tools",
    paymentMethod: "Transfer",
    amount: 400000,
  },
  {
    id: "tx-mei-add-05",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-05-05",
    petyCashNo: "PC-021",
    status: "Sudah Proses",
    description: "PENGGANTIAN PEMBAYARAN MESS 01 (PERIODE APRIL - MEI 2026)",
    category: "Mess karyawan",
    paymentMethod: "Tunai",
    amount: 4200000,
  },
  {
    id: "tx-mei-add-06",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-05-05",
    petyCashNo: "PC-021",
    status: "Sudah Proses",
    description: "PEMBAYARAN MESS 01 (PRIODE MEI - JUNI 2026)",
    category: "Mess karyawan",
    paymentMethod: "Tunai",
    amount: 4200000,
  },
  {
    id: "tx-mei-add-07",
    projectId: "proj-smart-marunda",
    type: "PetyCash",
    pic: "P Ujang",
    date: "2026-05-05",
    petyCashNo: "PC-021",
    status: "Sudah Proses",
    description: "PEMBELIAN AIR MINUM GALON (07 MEI sd 20 MEI 2026)",
    category: "Air Minum",
    paymentMethod: "Tunai",
    amount: 1600000,
  },

  // PO CONTRACT BREAKDOWNS (PO totals page 4 PO/WO = 1.779.800.000)
  {
    id: "po-1",
    projectId: "proj-smart-marunda",
    type: "PO",
    pic: "Bpk. FAISAL",
    date: "2026-04-01",
    invoiceNo: "B1.17.08.2026.04.07825",
    status: "Sudah PO",
    description: "PIPING WORKS CONTRACT PO",
    category: "Material",
    amount: 1100000000,
  },
  {
    id: "po-2",
    projectId: "proj-smart-marunda",
    type: "PO",
    pic: "Bpk. FAISAL",
    date: "2026-03-30",
    invoiceNo: "B1.17.08.2026.03.07579",
    status: "Sudah PO",
    description: "ELECTRICAL WORKS CONTRACT PO",
    category: "Material",
    amount: 330000000,
  },
  {
    id: "po-3",
    projectId: "proj-smart-marunda",
    type: "PO",
    pic: "Bpk. FAISAL",
    date: "2026-06-30",
    invoiceNo: "B1.17.08.2026.06.15391",
    status: "Sudah PO",
    description: "MEMBER SUPPLY MECHANICAL WORKS PERIODE MARET PO",
    category: "Material",
    amount: 58000000,
  },
  {
    id: "po-4",
    projectId: "proj-smart-marunda",
    type: "PO",
    pic: "Bpk. FAISAL",
    date: "2026-06-12",
    invoiceNo: "B1.17.08.2026.06.13725",
    status: "Sudah PO",
    description: "MAN POWER SUPPLY SCAFOLDER PERIODE MARET-APRIL PO",
    category: "Material",
    amount: 51000000,
  },

  // INVOICE INCOME (Total Pemasukan Invoice = Rp 634.920.000)
  {
    id: "inv-inc-1",
    projectId: "proj-smart-marunda",
    type: "Invoice",
    pic: "Mr. Faisal",
    date: "2026-04-07",
    invoiceNo: "068/MCJ_INV/04/2026",
    status: "Sudah Kirim Invoice",
    description: "DP 20% SMART PIPING INVOICE",
    category: "Ppn 11%", // Categories don't restrict transaction types but good to record
    amount: 220000000,
  },
  {
    id: "inv-inc-2",
    projectId: "proj-smart-marunda",
    type: "Invoice",
    pic: "Mr. Faisal",
    date: "2026-04-07",
    invoiceNo: "067/MCJ_INV/04/2026",
    status: "Sudah Kirim Invoice",
    description: "DP 20% SMART ELECTRICAL INVOICE",
    category: "Ppn 11%",
    amount: 66000000,
  },
  {
    id: "inv-inc-3",
    projectId: "proj-smart-marunda",
    type: "Invoice",
    pic: "Mr. Faisal",
    date: "2026-05-06",
    invoiceNo: "077/MCJ_INV/05/2026",
    status: "Sudah Kirim Invoice",
    description: "PROGRES 20% SMART PIPING INVOICE",
    category: "Ppn 11%",
    amount: 220000000,
  },
  {
    id: "inv-inc-4",
    projectId: "proj-smart-marunda",
    type: "Invoice",
    pic: "Mr. Faisal",
    date: "2026-05-06",
    invoiceNo: "078/MCJ_INV/05/2026",
    status: "Sudah Kirim Invoice",
    description: "PROGRES 20% SMART ELECTRICAL INVOICE",
    category: "Ppn 11%",
    amount: 66000000,
  },
  {
    id: "inv-inc-5",
    projectId: "proj-smart-marunda",
    type: "Invoice",
    pic: "Mr. Faisal",
    date: "2026-06-01",
    invoiceNo: "097/MCJ_INV/06-2026",
    status: "Sudah Kirim Invoice",
    description: "PROGRES 30% SMART PIPING INVOICE",
    category: "Ppn 11%",
    amount: 330000000,
  }
];

export const MONTHLY_BUDGETS_SEED: Record<string, MonthlyBudget[]> = {
  "proj-smart-marunda": [
    {
      month: "Januari",
      estimate: { piping: 0, electrical: 0, mechanical: 0, scafolder: 0 },
      po: { piping: 0, electrical: 0, mechanical: 0, scafolder: 0 },
      invoiceIncome: 0,
    },
    {
      month: "Februari",
      estimate: { piping: 1458900000, electrical: 499200000, mechanical: 0, scafolder: 0 },
      po: { piping: 1100000000, electrical: 330000000, mechanical: 0, scafolder: 0 },
      invoiceIncome: 0,
    },
    {
      month: "Maret",
      estimate: { piping: 0, electrical: 0, mechanical: 0, scafolder: 0 },
      po: { piping: 0, electrical: 0, mechanical: 0, scafolder: 0 },
      invoiceIncome: 0,
    },
    {
      month: "April",
      estimate: { piping: 0, electrical: 0, mechanical: 65040000, scafolder: 0 },
      po: { piping: 58000000, electrical: 0, mechanical: 58000000, scafolder: 0 },
      invoiceIncome: 317460000,
    },
    {
      month: "Mei",
      estimate: { piping: 60310000, electrical: 51710000, mechanical: 30450000, scafolder: 54200000 },
      po: { piping: 0, electrical: 46000000, mechanical: 26800000, scafolder: 51000000 },
      invoiceIncome: 317460000,
    },
    {
      month: "Juni",
      estimate: { piping: 0, electrical: 0, mechanical: 0, scafolder: 0 },
      po: { piping: 0, electrical: 0, mechanical: 73000000, scafolder: 37000000 },
      invoiceIncome: 0,
    }
  ]
};

export const CATEGORIES: Category[] = [
  "Gaji",
  "Material",
  "Consumable",
  "Tools",
  "Makan",
  "Air Minum",
  "Transportasi",
  "FEE MARKET",
  "Kopi Rokok",
  "Kesehatan",
  "Perlengkapan Pelindung",
  "Rental",
  "Mess karyawan",
  "Lain - Lain",
  "ATK",
  "Ppn 11%",
  "Dana 2%",
  "BPJS JAKON",
  "Pph 4%"
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: "act-1",
    type: "project",
    action: "Proyek Dibuat",
    description: "Membuat proyek baru [TSRT.SMART.001.2026] PT SMART MARUNDA",
    pic: "Administrator",
    date: "2026-03-01"
  },
  {
    id: "act-2",
    type: "po",
    action: "Material PO Tersimpan",
    description: "Menginput Purchase Order baru senilai Rp 1.100.000.000 untuk material Piping",
    pic: "P Haryanto",
    date: "2026-03-02"
  },
  {
    id: "act-3",
    type: "petycash_request",
    action: "Pengajuan Petty Cash",
    description: "Mengajukan dana petty cash sebesar Rp 2.500.000 untuk pembelian perlengkapan APD",
    pic: "P Haryanto",
    date: "2026-03-05"
  }
];
